### ISSUE TITLE
Problem with Option and column names

### ISSUE THREAD

**Issue by kurtie** [datanucleus/datanucleus-scala#3]
Hi,

   I don't know if this is the place for this. I apologize if it is not, but it is the best one I could find.

   I was able to figure how to use datanucleus-scala for using scala Option in persistent fields, but it only works when the name of the field and the name of the database row are the same. For instance:

```
@persistent
@column(name = "pais_telcode", jdbcType = "VARCHAR")
var phoneCode: Option[String] = None
```

Does not work as pais_telcode is ignored. It works if I do:

```
@persistent
var pais_telcode: Option[String] = None
```

   Because the field name now is the same as the row in database. Maybe I am doing something wrong?

   Best,
   Kurt.-

**Comment by renataogarcia** [comment]
Hi Kurt,

It's probably a bug - I'll have a look and let you know.

**Comment by renataogarcia** [comment]
datanucleus/datanucleus-rdbms#137 - should fix this.

**Comment by kurtie** [comment]
I downloaded the nightly build and works like a charm. Thanks a lot!
